# Generated by Django 6.0.5 on 2026-05-19 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitos',
            name='owner',
        ),
        migrations.AddField(
            model_name='habitos',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='habits.grupo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.IntegerField(max_length=8),
        ),
    ]
