# Generated by Django 6.0.5 on 2026-05-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habitos_owner_habitos_grupo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habitos',
            new_name='Tarea',
        ),
    ]
