# Generated by Django 6.0.5 on 2026-06-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_rename_habitos_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.IntegerField(),
        ),
    ]
