# Generated by Django 6.0.5 on 2026-06-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_rol_persona_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='grupo',
        ),
        migrations.AddField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='personas',
            field=models.ManyToManyField(related_name='tareas', to='habits.persona'),
        ),
    ]
