# Generated by Django 6.0.5 on 2026-06-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_remove_tarea_grupo_tarea_completada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='dificultad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=10),
        ),
    ]
