# Generated by Django 6.0.5 on 2026-06-25 15:17

from django.db import migrations, models


def convertir_dificultades(apps, schema_editor):
    Tarea = apps.get_model('habits', 'Tarea')
    Tarea.objects.filter(dificultad='Baja').update(dificultad='1')
    Tarea.objects.filter(dificultad='Media').update(dificultad='2')
    Tarea.objects.filter(dificultad='Alta').update(dificultad='3')


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_tarea_dificultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='google_calendar_sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(convertir_dificultades, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tarea',
            name='dificultad',
            field=models.CharField(choices=[('1', '1 - Baja'), ('2', '2 - Media'), ('3', '3 - Alta')], default='1', max_length=1),
        ),
    ]
